###

GET http://localhost:8095/api/negociations/1


###

POST   http://localhost:8090/api/users/1
Content-Type: application/json

{   
  "firstName": "iouheruf",
  "lastName": "iuhuf",
  "dateNaissance": null,
  "gender": null,
  "imageProfile": null,
  "email": null,
  "phone": null,
  "address": "poejfio",
  "nationality": null,
  "cne": "oirefjirf",
  "login": "oiuzjef",
  "password": "oizjfiozfj",
  "roles": []
}

###

PUT http://localhost:8090/api/users/1
Content-Type: application/json

{
"firstName": "NewFirstName",
"lastName": "NewLastName",
"address": "NewAddress",
"cne": "NewCNE",
"login": "NewLogin",
"password": "NewPassword"
}

###

DELETE http://localhost:8090/api/users/2
